### ISSUE TITLE
~Wallaby() destructor/constructor & removing console output

### ISSUE THREAD

**Issue by Zacharyprime** [kipr/libwallaby#152]
When the program exits on the Wombat, it shows the destructor ~Wallaby() on the console output. 

Carol pointed this out to me while doing a workshop so I presume it confused a student/teacher.

This is connected to https://github.com/kipr/KIPR-Update/issues/15

**Comment by Zacharyprime** [comment]
Braden has wanted the outputting of the destructor and motors stopping for a while.

In the process of this we can suppress that output to console

**Comment by bmcdorman** [comment]
Handled by #164
