### ISSUE TITLE
Standardize formatting

### ISSUE THREAD

**Issue by chrehall68** [kipr/libwallaby#157]
Formatting is kinda inconsistent...

I suggest there be a standard ruleset. It could be explicitly put in the readme in a separate section marked 'formatting'.

**Comment by Zacharyprime** [comment]
What exactly do you mean by formatting.

Not that I disagree, there are just a lot of contexts that your statement would make sense in.

**Comment by Zacharyprime** [comment]
I'm still not sure what this meant.
This issue is too broad to represent any specific goal so I am going to close it.

If this is still a problem, feel free to create a new issue but please be specific or give a metric for what it would mean to accomplish the goal.
