### ISSUE TITLE
No language bindings

### ISSUE THREAD

**Issue by bowbahdoe** [kipr/libwallaby#39]
Lack of bindings for python and java renders programs written in those languages incompatible with wallaby.

**Comment by jsoutherland** [comment]
@bowbahdoe thanks, we'll try to get this fixed soon.

**Comment by jsoutherland** [comment]
@bowbahdoe I hope to get to this next week. We were working on update 10 and now need to get camera support and ethernet over USB first.

**Comment by jsoutherland** [comment]
@bowbahdoe We have python mostly working now.  It should be available via an update (16) later this week.
