### ISSUE TITLE
Where are the new firmware versions?

### ISSUE THREAD

**Issue by ryanvade** [kipr/libwallaby#86]
Firmware updates have been pushed out to the Wallabies but haven't been pushed to this repo. Are they somewhere else?

**Comment by jsoutherland** [comment]
Hi @ryanvade I haven't been involved in active development for a while.  I believe you may be looking for the PRs listed here:
https://github.com/kipr/meta-kipr/pulls?q=is%3Apr+is%3Aclosed

Which version are you on now?

**Comment by ryanvade** [comment]
I've seen a V26 floating around, which I can't seem to find on the list of PRs.

**Comment by jsoutherland** [comment]
I'm not sure what's going on there.  Only 24 exists on github (as an open PR in meta-kipr).  

@navzam @bmcdorman @musghz  any info?
